name: intex_commerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # For GetX
  get: ^4.6.5

  # For local database
  get_storage: ^2.0.3

  # For loading images from server
  cached_network_image: ^3.2.1

  # For responsiveness
  flutter_screenutil: ^5.5.3+2

  # For checking responsiveness
  device_preview: ^1.1.0

  # For lottie animations
  lottie: ^1.4.1

  # For shimmer effect
  shimmer: ^2.0.0

  # For network
  dio: ^4.0.6

  # For console outputs
  logger: ^1.1.0

  # To dismiss keyboard
  keyboard_dismisser: ^3.0.0

  # To refresh
  liquid_pull_to_refresh: ^3.0.1

  # To launching urls
  url_launcher: ^6.1.5

  # To check connection
  internet_connection_checker: ^0.0.1+4

  # To form text field
  flutter_masked_text2: ^0.9.1

  # To secure urls
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/lottie/
    - assets/png/icons/
    - assets/png/local/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
